# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

assets: http://aelaa.github.io/assets
# baseurl: http://127.0.0.1:4000

# pagination
paginate: 10

languages: ["ru", "en"]#, "ko", "zh"]

# Markdown Processors
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - tables
    - lax_spacing
    - with_toc_data


title : aelaa's Blog
# tagline:


##### Menu
home_path: /
archives_path: /archives
about_path: /about
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

widgets:
- category
- tag
- links
- rss


rss: /atom.xml

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/logo.png        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.
apple_icon: img/jacman.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: img/author.jpg ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.
banner_img: #img/banner.jpg ## size:1920px*200px+. Banner Picture

#### index post is expanding or not
index:
  expand: true           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: Read More

#### Author information
author:
  name: aelaa
  intro_line1: "За шаблон сайта спасибо Yitao"
  intro_line2: ""
  email: aelaau@gmail.com
  twitter: aelaau
  github: aelaa
  facebook: aelaa
  linkedin:
## if you set them, the corresponding  share button will show on the footer


links:
  Hexlet: http://hexlet.io

excerpt_separator: <!--more-->

#### Comment
disqus_shortname: aelaa

#### Miscellaneous
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true

gems:
 - jemoji
 - jekyll-paginate
